### ISSUE TITLE
Reworking some Julia AST forms

### ISSUE THREAD

**Issue by c42f** [JuliaLang/JuliaSyntax.jl#88]
With JuliaSyntax, we've got our own green tree (`GreenNode`) and AST (`SyntaxNode`) which often differ from `Expr`, due to the requirement that children are strictly in source order.  Some current differences are described in https://github.com/JuliaLang/JuliaSyntax.jl#tree-differences-between-greennode-and-expr. Given that we've been forced to diverge we might as well make the most of this and reconsider some aspects of `Expr` for two reasons:

* To give extra textural information to users of green tree (eg, presence of parentheses), without the need to recompute this information by inspecting the trivia. (These nodes will probably be elided during AST conversion?)
* To give extra information to AST users like macro writers (eg, conditional ternary is the same as `:if` for `Expr` users)

List of possible changes

* [x] Insertion of extra blocks inconsistent in various places, sometimes due to the need of `Expr` to hold `LineNumberNode`.  Avoid this!
    * [x] `let` argument lists (#126)
    * [x] short form functions have a block for the body line number
    * [x] `elseif` conditional has a block for the line number
    * [x] anon function `->` has a block only for the body line number
* [x] Containers for string-like constructs - these are very useful for tooling which works with the tokens of the source text. Also separating the delimiters from the text they delimit removes a whole class of tokenization errors and lets the parser deal with them.
    * [x] string (always use K"string" to wrap strings, even when they only contain a single `K"String"` token. See #94)
    * [x] char (add a new `K"char"` for containing characters along with their delimiters?). See #121 
    * [x] backticks (use `K"`"` or add `K"backticks"`?)
    * [x] `var""` syntax (use `K"var"`? as the head?) (#127)
* [x] Faithful representation of the source text / avoid premature lowering
    * [x] `K"macrocall"` - allow users to easily distinguish macrocalls with parentheses from those without them (#218)
    * [x] parentheses  (`K"parens"`)
    * [x] Ternary conditional (#85)
    * [x] `global const` is normalized to `const global` in the parser. Should be done in `Expr` conversion (#130)
    * [x] The AST for `do` seems partially lowered. Should it be flatter like `f(x) do y ; body end` being `(do (call f) (tuple y) (block body))`? (#98)
    * [x] Lower `@.` to `@__dot__` later, not inside parser
    * [x] Lower docstrings to `Core.@doc` later, not inside parser (#217)
* [x] Improvements for AST inconsistencies
    * [x] The AST for dotted infix calls like `a .+ b` is inconsistent with prefix calls like `f.(a, b)` (see #90)
    * [x] "Standalone" dotted operators are parsed inconsistently.  For example `.*(x,y) ==> (call .* x y)` vs `(.*)(x,y)  ==>  (call (. *) x y)` ie, there's a dotted symbol vs `Expr(:.)` in these cases (see discussion in #90)
    * [x] Inconsistent use of `=` vs `kw` (#99)
    * [x] Emit unadorned postfix adjoint with a `call` head rather than as a syntactic operator for consistency with suffixed versions like `x'ᵀ` (#124 )
 * [x] Improvements to awkward AST forms
    * [x] Frakentuples with multiple parameter blocks like `(a=1, b=2; c=3; d=4)` are a weird nested structure. Let's flatten this and bring the multiple sets of `K"parameters" into the parent tuple. (#133)
    * [x] try-catch-else-finally is very awkward with its optional children. Is there something we can/should do about this?  How about lowering `try body1 catch exc body2 else body3 finally body4 end`  to `(try body1 (catch exc body2) (else body3) (finally body4))` (#234)
    * [x] Import paths `import A.b.c` are different from normal `A.b.c`.  Use a different head for these.
    * [x] Some constructs have a first child which serves as a flag, for example whether `mutable` is present in a `struct` and whether a module is actually `baremodule`. These seem more like part of the expression head - would they be better as flags?

### Considered and rejected for now

* [x] `:toplevel` expressions occur both at file scope and as `;`-delimited expressions at file scope. This seems kind of weird?
* [x] Is it possible to improve the representation of `global x,y` vs `global x` vs `global (x,y) = (1,2)` vs `global (x,y)`?  (In particular, the variables might or might not be enclosed in a tuple.)
* [x] Lower cmd strings to `Core.@cmd` later, not inside parser
* [x] Lower custom string and cmd macros to `macrocall` later, not inside parser
* [x] Infix vs prefix calls - should this be managed in flags or a kind like `K"infix_call"`? (considered and decided against in #99 and  #124)

**Comment by c42f** [comment]
I think this is done for now. It's become quite an epic list of changes :grimacing:

There might be more but they can go in separate issues I guess.

**Comment by timholy** [comment]
Seems like a considerable increase in consistency!

**Comment by c42f** [comment]
Thanks I hope so!  It added up to a lot of rearrangement :-)
